import type { Metadata } from "next";
import { Fira_Sans_Condensed, Inter } from "next/font/google";
import "./globals.css";
import Providers from "./providers";
import Header from "../components/Header";

const firaSansCondensed = Fira_Sans_Condensed({
  subsets: ["latin"],
  weight: ["100", "200", "300", "400", "500", "600", "700", "800", "900"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={firaSansCondensed.className}>
        <Providers>
          <Header />
          <div className="w-11/12 md:w-10/12 lg:w-9/12 mx-auto">
          {children}
          </div>
        </Providers>
      </body>
    </html>
  );
}
