import type { Metadata } from "next";
import { Fira_Sans_Condensed, Inter } from "next/font/google";
import "./globals.css";
import Providers from "./providers";

const firaSansCondensed = Fira_Sans_Condensed({
  subsets: ["latin"],
  weight: ["100", "200", "300", "400", "500", "600", "700", "800", "900"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={firaSansCondensed.className}>
        <Providers>{children}</Providers>
      </body>
    </html>
  );
}
